# Generated by Django 3.2.7 on 2023-11-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewText',
        ),
    ]
